#
#
#	CONFIG BUNDLE angularBundle
#
#===============================================================================
#
#  Copyright © 2017/2018        admin | admin@nodefony.com
#
# ===============================================================================
#
#        GENERATE BY nodefony BUILDER YAML FILE
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
#
#

########## nodefony CONFIG ANGULAR BUNDLE TYPE  angularBundle  ############
name        : angularBundle
version     : "1.0.0"
locale      : en_en
type        : "angular"

#
#  WATCHERS
#
#    watchers Listen to changes, deletion, renaming of files and directories
#    of different components
#
#    For watch all components
#
#      watch:			true
#    or
#      watch:
#        controller:		true
#        config:                true		# only  routing.yml
#        views:			true
#        translations:          true
#
watch:				true

#
#
#	Insert here the bundle-specific configurations
#
#	You can also override config of another bundle
#	with the name of the bundle
#
#	example : create an other database connector
#
